# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-03 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'', max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=b'images/misc')),
            ],
        ),
        migrations.CreateModel(
            name='MiscCoverImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'images/miscCover')),
            ],
        ),
    ]
