# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-10 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20161012_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverimage',
            name='image',
            field=models.ImageField(upload_to=b'images/ritu'),
        ),
    ]
