# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20161110_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=b'', max_length=120),
        ),
    ]
